version: "3.4"
services:
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
  web:
    build: .
    image: custom-pi-air-quality-monitor
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
        - REDIS_HOST=redis
        - PORT=8001
    volumes:
      - ./src:/code
    depends_on:
      - "redis"
    ports:
      - "8001:8001"
